version: '3.3'

services:

  redis:
    image: redis:7
    ports:
      - 6379:6379

  db:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: service
      POSTGRES_DB: service
      POSTGRES_PASSWORD: letmeeeen

