spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:service}
    username: ${DB_USER:service}
    password: ${DB_PASS:letmeeeen}
    driver-class-name: org.postgresql.Driver

  data.redis:
    host: ${REDIS_HOSTNAME:localhost}
    port: 6379

  cache.type: redis
